// Generated by gencpp from file fetch_train/EePose.msg
// DO NOT EDIT!


#ifndef FETCH_TRAIN_MESSAGE_EEPOSE_H
#define FETCH_TRAIN_MESSAGE_EEPOSE_H

#include <ros/service_traits.h>


#include <fetch_train/EePoseRequest.h>
#include <fetch_train/EePoseResponse.h>


namespace fetch_train
{

struct EePose
{

typedef EePoseRequest Request;
typedef EePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EePose
} // namespace fetch_train


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_train::EePose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::fetch_train::EePose&) { return value(); }
};

template<>
struct DataType< ::fetch_train::EePose > {
  static const char* value()
  {
    return "fetch_train/EePose";
  }

  static const char* value(const ::fetch_train::EePose&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_train::EePoseRequest> should match 
// service_traits::MD5Sum< ::fetch_train::EePose > 
template<>
struct MD5Sum< ::fetch_train::EePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EePose >::value();
  }
  static const char* value(const ::fetch_train::EePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EePoseRequest> should match 
// service_traits::DataType< ::fetch_train::EePose > 
template<>
struct DataType< ::fetch_train::EePoseRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EePose >::value();
  }
  static const char* value(const ::fetch_train::EePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_train::EePoseResponse> should match 
// service_traits::MD5Sum< ::fetch_train::EePose > 
template<>
struct MD5Sum< ::fetch_train::EePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EePose >::value();
  }
  static const char* value(const ::fetch_train::EePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EePoseResponse> should match 
// service_traits::DataType< ::fetch_train::EePose > 
template<>
struct DataType< ::fetch_train::EePoseResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EePose >::value();
  }
  static const char* value(const ::fetch_train::EePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_TRAIN_MESSAGE_EEPOSE_H
