// Generated by gencpp from file fetch_train/EeRpy.msg
// DO NOT EDIT!


#ifndef FETCH_TRAIN_MESSAGE_EERPY_H
#define FETCH_TRAIN_MESSAGE_EERPY_H

#include <ros/service_traits.h>


#include <fetch_train/EeRpyRequest.h>
#include <fetch_train/EeRpyResponse.h>


namespace fetch_train
{

struct EeRpy
{

typedef EeRpyRequest Request;
typedef EeRpyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EeRpy
} // namespace fetch_train


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_train::EeRpy > {
  static const char* value()
  {
    return "cfb6f20560ab4d9cc1d682755cf3b5d4";
  }

  static const char* value(const ::fetch_train::EeRpy&) { return value(); }
};

template<>
struct DataType< ::fetch_train::EeRpy > {
  static const char* value()
  {
    return "fetch_train/EeRpy";
  }

  static const char* value(const ::fetch_train::EeRpy&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_train::EeRpyRequest> should match 
// service_traits::MD5Sum< ::fetch_train::EeRpy > 
template<>
struct MD5Sum< ::fetch_train::EeRpyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EeRpy >::value();
  }
  static const char* value(const ::fetch_train::EeRpyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EeRpyRequest> should match 
// service_traits::DataType< ::fetch_train::EeRpy > 
template<>
struct DataType< ::fetch_train::EeRpyRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EeRpy >::value();
  }
  static const char* value(const ::fetch_train::EeRpyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_train::EeRpyResponse> should match 
// service_traits::MD5Sum< ::fetch_train::EeRpy > 
template<>
struct MD5Sum< ::fetch_train::EeRpyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EeRpy >::value();
  }
  static const char* value(const ::fetch_train::EeRpyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EeRpyResponse> should match 
// service_traits::DataType< ::fetch_train::EeRpy > 
template<>
struct DataType< ::fetch_train::EeRpyResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EeRpy >::value();
  }
  static const char* value(const ::fetch_train::EeRpyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_TRAIN_MESSAGE_EERPY_H
