// Generated by gencpp from file fetch_train/EeTraj.msg
// DO NOT EDIT!


#ifndef FETCH_TRAIN_MESSAGE_EETRAJ_H
#define FETCH_TRAIN_MESSAGE_EETRAJ_H

#include <ros/service_traits.h>


#include <fetch_train/EeTrajRequest.h>
#include <fetch_train/EeTrajResponse.h>


namespace fetch_train
{

struct EeTraj
{

typedef EeTrajRequest Request;
typedef EeTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EeTraj
} // namespace fetch_train


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_train::EeTraj > {
  static const char* value()
  {
    return "28e4dd667b29bd35b516ba1d379b7529";
  }

  static const char* value(const ::fetch_train::EeTraj&) { return value(); }
};

template<>
struct DataType< ::fetch_train::EeTraj > {
  static const char* value()
  {
    return "fetch_train/EeTraj";
  }

  static const char* value(const ::fetch_train::EeTraj&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_train::EeTrajRequest> should match 
// service_traits::MD5Sum< ::fetch_train::EeTraj > 
template<>
struct MD5Sum< ::fetch_train::EeTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EeTraj >::value();
  }
  static const char* value(const ::fetch_train::EeTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EeTrajRequest> should match 
// service_traits::DataType< ::fetch_train::EeTraj > 
template<>
struct DataType< ::fetch_train::EeTrajRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EeTraj >::value();
  }
  static const char* value(const ::fetch_train::EeTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_train::EeTrajResponse> should match 
// service_traits::MD5Sum< ::fetch_train::EeTraj > 
template<>
struct MD5Sum< ::fetch_train::EeTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::EeTraj >::value();
  }
  static const char* value(const ::fetch_train::EeTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::EeTrajResponse> should match 
// service_traits::DataType< ::fetch_train::EeTraj > 
template<>
struct DataType< ::fetch_train::EeTrajResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_train::EeTraj >::value();
  }
  static const char* value(const ::fetch_train::EeTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_TRAIN_MESSAGE_EETRAJ_H
