// Generated by gencpp from file fetch_train/JointTraj.msg
// DO NOT EDIT!


#ifndef FETCH_TRAIN_MESSAGE_JOINTTRAJ_H
#define FETCH_TRAIN_MESSAGE_JOINTTRAJ_H

#include <ros/service_traits.h>


#include <fetch_train/JointTrajRequest.h>
#include <fetch_train/JointTrajResponse.h>


namespace fetch_train
{

struct JointTraj
{

typedef JointTrajRequest Request;
typedef JointTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointTraj
} // namespace fetch_train


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_train::JointTraj > {
  static const char* value()
  {
    return "3fc8a9e27b55b9b20a2c846f9e053a5c";
  }

  static const char* value(const ::fetch_train::JointTraj&) { return value(); }
};

template<>
struct DataType< ::fetch_train::JointTraj > {
  static const char* value()
  {
    return "fetch_train/JointTraj";
  }

  static const char* value(const ::fetch_train::JointTraj&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_train::JointTrajRequest> should match 
// service_traits::MD5Sum< ::fetch_train::JointTraj > 
template<>
struct MD5Sum< ::fetch_train::JointTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::JointTraj >::value();
  }
  static const char* value(const ::fetch_train::JointTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::JointTrajRequest> should match 
// service_traits::DataType< ::fetch_train::JointTraj > 
template<>
struct DataType< ::fetch_train::JointTrajRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_train::JointTraj >::value();
  }
  static const char* value(const ::fetch_train::JointTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_train::JointTrajResponse> should match 
// service_traits::MD5Sum< ::fetch_train::JointTraj > 
template<>
struct MD5Sum< ::fetch_train::JointTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_train::JointTraj >::value();
  }
  static const char* value(const ::fetch_train::JointTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_train::JointTrajResponse> should match 
// service_traits::DataType< ::fetch_train::JointTraj > 
template<>
struct DataType< ::fetch_train::JointTrajResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_train::JointTraj >::value();
  }
  static const char* value(const ::fetch_train::JointTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_TRAIN_MESSAGE_JOINTTRAJ_H
