(cl:defpackage fetch_train-srv
  (:use )
  (:export
   "EEPOSE"
   "<EEPOSE-REQUEST>"
   "EEPOSE-REQUEST"
   "<EEPOSE-RESPONSE>"
   "EEPOSE-RESPONSE"
   "EERPY"
   "<EERPY-REQUEST>"
   "EERPY-REQUEST"
   "<EERPY-RESPONSE>"
   "EERPY-RESPONSE"
   "EETRAJ"
   "<EETRAJ-REQUEST>"
   "EETRAJ-REQUEST"
   "<EETRAJ-RESPONSE>"
   "EETRAJ-RESPONSE"
   "JOINTTRAJ"
   "<JOINTTRAJ-REQUEST>"
   "JOINTTRAJ-REQUEST"
   "<JOINTTRAJ-RESPONSE>"
   "JOINTTRAJ-RESPONSE"
  ))

